zookeeper:
  image: eventuateio/eventuate-zookeeper:0.9.0.RC3
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888

kafka:
  image: eventuateio/eventuate-kafka:0.9.0.RC2
  ports:
    - 9092:9092
  links:
    - zookeeper
  environment:
    - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
    - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
    - ZOOKEEPER_SERVERS=zookeeper:2181
    - ZOOKEEPER_CONNECTION_TIMEOUT_MS=60000

mysql:
  image: eventuateio/eventuate-mysql:0.9.0.RC3
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_USER=mysqluser
    - MYSQL_PASSWORD=mysqlpw

activemq:
  image: eventuateio/eventuate-activemq:0.3.0.RELEASE
  ports:
    - 8161:8161
    - 61616:61616
    - 61613:61613
    - 1883:1883
    - 61614:61614

rabbitmq:
  image: eventuateio/eventuate-rabbitmq:0.3.0.RELEASE
  ports:
    - 5672:5672

redis:
  image: redis:5.0.3
  ports:
    - 6379:6379

cdcservice:
  build: ./eventuate-cdc-service
  ports:
    - "8099:8080"
  links:
    - mysql
    - kafka
    - zookeeper
    - activemq
    - rabbitmq
    - redis
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
    EVENTUATELOCAL_CDC_POLLING_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_MAX_EVENTS_PER_POLLING: 1000
    EVENTUATELOCAL_CDC_MAX_ATTEMPTS_FOR_POLLING: 100
    EVENTUATELOCAL_CDC_POLLING_RETRY_INTERVAL_IN_MILLISECONDS: 500
    EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
    EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog
    EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
    EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
    EVENTUATE_CDC_TYPE: EventuateLocal
    #    SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ACTIVEMQ_URL: tcp://activemq:61616
    ACTIVEMQ_USER: eventuateuser
    ACTIVEMQ_PASSWORD: eventuatepassword
    RABBITMQ_URL: rabbitmq
    EVENTUATE_REDIS_SERVERS: redis:6379
    EVENTUATE_REDIS_PARTITIONS: 1
